name: KongTestCI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start kong cp servers and install cypress
        run: |
          docker compose -f kong.yaml up -d
          npm install cypress --save-dev
          npm install pg
          
      - name: cypress run against kong cp servers.
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:8002/workspaces' # Waits for kong cp servers
          # Records to Cypress Cloud
          # eg, visit private project result site: https://cloud.cypress.io/projects/ijucgi/runs/10
          record: true
          browser: chrome 
        env:
          # For recording set CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
          

         

