# The Assignment
# During your first panel interview, you received login credentials for http://localhost:8002/login.
# Use these to create an E2E test suite for the Gateway Service.
# Information about Gateway Service can be found here:
# https://docs.konghq.com/gateway/latest/key-concepts/services.
# Information about deploying Gateway with docker can be found here:
# https://docs.konghq.com/gateway/latest/install/docker/
# Information about Gateway Configuration (if required) can be found here:
# https://docs.konghq.com/gateway/3.8.x/reference/configuration/
# You have the freedom to choose your toolchain (Cypress with JS or TS).
# Setup:
# - Download the docker-compose file
# - Navigate to the directory where the docker-compose.yml file is located
# - Run docker-compose up -d
# - Navigate to http://localhost:8002/ in your browser
# - Make sure you can access the Kong Gateway UI (Kong Manager)
# Basic test actions:
# - Complete the flow to create a new Service from scratch using the UI of the application
# - Create any additional entities associated with a Service (e.g. Route)
# Bonus ideas:
# - Test Result Reporting
# - Continuous integration (run the tests in CI e.g. GitHub Actions)
# Teardown:
# - Run docker-compose down to shut down docker services
# How to submit the project
# You have one week to complete this, but we don't expect you to spend more than a few days on
# it.
# When it's ready, please send your recruiter a link to the source code, preferably in a GitHub
# public repo.
# Include a README in your project for local setup and execution. In this, describe your design
# considerations, assumptions, and trade-offs made during the exercise


name: KongTestCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Start kong cp server
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          docker compose -f kong.yaml up -d
          echo sleep 30 seconds, waiting server starting.
          sleep 30
          docker ps
          echo I feel Good here.
          ifconfig -a
          #curl http://localhost:8002/workspaces
          
      # Check if deployment is good.    
      - name: check deployment result
        run: |
          curl http://localhost:8002/workspaces
          pwd
          ls
          #docker run -v $PWD:/cypress -w /cypress cypress/included 
          npm install cypress --save-dev
          pwd
          npx cypress run
          
          

         

