# The Assignment
# During your first panel interview, you received login credentials for http://localhost:8002/login.
# Use these to create an E2E test suite for the Gateway Service.
# Information about Gateway Service can be found here:
# https://docs.konghq.com/gateway/latest/key-concepts/services.
# Information about deploying Gateway with docker can be found here:
# https://docs.konghq.com/gateway/latest/install/docker/
# Information about Gateway Configuration (if required) can be found here:
# https://docs.konghq.com/gateway/3.8.x/reference/configuration/
# You have the freedom to choose your toolchain (Cypress with JS or TS).
# Setup:
# - Download the docker-compose file
# - Navigate to the directory where the docker-compose.yml file is located
# - Run docker-compose up -d
# - Navigate to http://localhost:8002/ in your browser
# - Make sure you can access the Kong Gateway UI (Kong Manager)
# Basic test actions:
# - Complete the flow to create a new Service from scratch using the UI of the application
# - Create any additional entities associated with a Service (e.g. Route)
# Bonus ideas:
# - Test Result Reporting
# - Continuous integration (run the tests in CI e.g. GitHub Actions)
# Teardown:
# - Run docker-compose down to shut down docker services
# How to submit the project
# You have one week to complete this, but we don't expect you to spend more than a few days on
# it.
# When it's ready, please send your recruiter a link to the source code, preferably in a GitHub
# public repo.
# Include a README in your project for local setup and execution. In this, describe your design
# considerations, assumptions, and trade-offs made during the exercise


name: KongTestCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Start kong cp server
        run: |
          echo start kong cp servers
          pwd
          ls
          pwd
          echo ------
          docker compose -f kong.yaml up -d
          npm install cypress --save-dev
          
      - name: cypress run
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: npx cypress run --record --key 94b4c566-4084-475a-b98f-099702c89ef3
          wait-on: 'http://localhost:8002/workspaces' # Waits for above
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: false # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        # with: 
        #     curl http://localhost:8002/workspaces
        #     npm install cypress --save-dev
        #     npx cypress run
          
          

         

